import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/sonner";
import { UiFontProvider } from "@/components/theme/ui-font-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                var s = localStorage.getItem("pos_store_settings");
                if (s) {
                  var p = JSON.parse(s);
                  if (p.uiFontSize) document.documentElement.setAttribute("data-ui-font-size", p.uiFontSize);
                  if (p.uiFontWeight) document.documentElement.setAttribute("data-ui-font-weight", p.uiFontWeight);
                  if (p.uiFontFamily) document.documentElement.setAttribute("data-ui-font-family", p.uiFontFamily);
                } else {
                  document.documentElement.setAttribute("data-ui-font-size", "md");
                  document.documentElement.setAttribute("data-ui-font-weight", "normal");
                  document.documentElement.setAttribute("data-ui-font-family", "sans");
                }
              } catch(e) {}
            `,
          }}
        />
      </head>
      <body className="min-h-screen flex flex-col overflow-x-hidden">
        <UiFontProvider />
        <TooltipProvider>
          {children}
          <Toaster />
        </TooltipProvider>
      </body>
    </html>
  );
}
